version: "3.6"

services:
  postgres:
    image: postgres:11-alpine
    networks:
      - chat-app
  smtp:
    image: mailhog/mailhog
    networks:
      - chat-app
  api:
    image: docker.pkg.github.com/akrantz01/apcsp/chat-app-api:v3
    ports:
      - "8080:80"
    environment:
      CHAT_HTTP_HOST: 0.0.0.0
      CHAT_HTTP_PORT: 80
      CHAT_HTTP_DOMAIN: http://127.0.0.1:8080
      CHAT_DATABASE_HOST: postgres
      CHAT_EMAIL_HOST: smtp
      CHAT_EMAIL_PORT: 1025
    networks:
      - chat-app
    depends_on:
      - postgres
      - smtp

networks:
  chat-app:
